// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: social.proto

package socialpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowUserRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type FollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	mi := &file_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowUserRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *UnfollowUserRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type UnfollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserResponse) Reset() {
	*x = UnfollowUserResponse{}
	mi := &file_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserResponse) ProtoMessage() {}

func (x *UnfollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserResponse.ProtoReflect.Descriptor instead.
func (*UnfollowUserResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`  // e.g. 20
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // last seen follow_id or timestamp for BTree thing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{5}
}

func (x *GetFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowingRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FollowingEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeId    string                 `protobuf:"bytes,1,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	FollowedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowingEdge) Reset() {
	*x = FollowingEdge{}
	mi := &file_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowingEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowingEdge) ProtoMessage() {}

func (x *FollowingEdge) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowingEdge.ProtoReflect.Descriptor instead.
func (*FollowingEdge) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{6}
}

func (x *FollowingEdge) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

func (x *FollowingEdge) GetFollowedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowedAt
	}
	return nil
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     []*FollowingEdge       `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowingResponse) GetFollowing() []*FollowingEdge {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *GetFollowingResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{8}
}

func (x *GetFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowersRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FollowerEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerEdge) Reset() {
	*x = FollowerEdge{}
	mi := &file_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerEdge) ProtoMessage() {}

func (x *FollowerEdge) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerEdge.ProtoReflect.Descriptor instead.
func (*FollowerEdge) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{9}
}

func (x *FollowerEdge) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowerEdge) GetFollowedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowedAt
	}
	return nil
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*FollowerEdge        `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{10}
}

func (x *GetFollowersResponse) GetFollowers() []*FollowerEdge {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *GetFollowersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_social_proto protoreflect.FileDescriptor

const file_social_proto_rawDesc = "" +
	"\n" +
	"\fsocial.proto\x12\x06social\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x11FollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\".\n" +
	"\x12FollowUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x13UnfollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\"0\n" +
	"\x14UnfollowUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"b\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.social.PaginationR\n" +
	"pagination\"m\n" +
	"\rFollowingEdge\x12\x1f\n" +
	"\vfollowee_id\x18\x01 \x01(\tR\n" +
	"followeeId\x12;\n" +
	"\vfollowed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"followedAt\"l\n" +
	"\x14GetFollowingResponse\x123\n" +
	"\tfollowing\x18\x01 \x03(\v2\x15.social.FollowingEdgeR\tfollowing\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"b\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.social.PaginationR\n" +
	"pagination\"l\n" +
	"\fFollowerEdge\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12;\n" +
	"\vfollowed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"followedAt\"k\n" +
	"\x14GetFollowersResponse\x122\n" +
	"\tfollowers\x18\x01 \x03(\v2\x14.social.FollowerEdgeR\tfollowers\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor2\xb5\x02\n" +
	"\rFollowService\x12C\n" +
	"\n" +
	"FollowUser\x12\x19.social.FollowUserRequest\x1a\x1a.social.FollowUserResponse\x12I\n" +
	"\fUnfollowUser\x12\x1b.social.UnfollowUserRequest\x1a\x1c.social.UnfollowUserResponse\x12I\n" +
	"\fGetFollowing\x12\x1b.social.GetFollowingRequest\x1a\x1c.social.GetFollowingResponse\x12I\n" +
	"\fGetFollowers\x12\x1b.social.GetFollowersRequest\x1a\x1c.social.GetFollowersResponseB\vZ\tsocialpb/b\x06proto3"

var (
	file_social_proto_rawDescOnce sync.Once
	file_social_proto_rawDescData []byte
)

func file_social_proto_rawDescGZIP() []byte {
	file_social_proto_rawDescOnce.Do(func() {
		file_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)))
	})
	return file_social_proto_rawDescData
}

var file_social_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_social_proto_goTypes = []any{
	(*FollowUserRequest)(nil),     // 0: social.FollowUserRequest
	(*FollowUserResponse)(nil),    // 1: social.FollowUserResponse
	(*UnfollowUserRequest)(nil),   // 2: social.UnfollowUserRequest
	(*UnfollowUserResponse)(nil),  // 3: social.UnfollowUserResponse
	(*Pagination)(nil),            // 4: social.Pagination
	(*GetFollowingRequest)(nil),   // 5: social.GetFollowingRequest
	(*FollowingEdge)(nil),         // 6: social.FollowingEdge
	(*GetFollowingResponse)(nil),  // 7: social.GetFollowingResponse
	(*GetFollowersRequest)(nil),   // 8: social.GetFollowersRequest
	(*FollowerEdge)(nil),          // 9: social.FollowerEdge
	(*GetFollowersResponse)(nil),  // 10: social.GetFollowersResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_social_proto_depIdxs = []int32{
	4,  // 0: social.GetFollowingRequest.pagination:type_name -> social.Pagination
	11, // 1: social.FollowingEdge.followed_at:type_name -> google.protobuf.Timestamp
	6,  // 2: social.GetFollowingResponse.following:type_name -> social.FollowingEdge
	4,  // 3: social.GetFollowersRequest.pagination:type_name -> social.Pagination
	11, // 4: social.FollowerEdge.followed_at:type_name -> google.protobuf.Timestamp
	9,  // 5: social.GetFollowersResponse.followers:type_name -> social.FollowerEdge
	0,  // 6: social.FollowService.FollowUser:input_type -> social.FollowUserRequest
	2,  // 7: social.FollowService.UnfollowUser:input_type -> social.UnfollowUserRequest
	5,  // 8: social.FollowService.GetFollowing:input_type -> social.GetFollowingRequest
	8,  // 9: social.FollowService.GetFollowers:input_type -> social.GetFollowersRequest
	1,  // 10: social.FollowService.FollowUser:output_type -> social.FollowUserResponse
	3,  // 11: social.FollowService.UnfollowUser:output_type -> social.UnfollowUserResponse
	7,  // 12: social.FollowService.GetFollowing:output_type -> social.GetFollowingResponse
	10, // 13: social.FollowService.GetFollowers:output_type -> social.GetFollowersResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_social_proto_init() }
func file_social_proto_init() {
	if File_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_proto_goTypes,
		DependencyIndexes: file_social_proto_depIdxs,
		MessageInfos:      file_social_proto_msgTypes,
	}.Build()
	File_social_proto = out.File
	file_social_proto_goTypes = nil
	file_social_proto_depIdxs = nil
}
