// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/social-service/social.proto

package socialpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_internal_social_service_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowUserRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type FollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	mi := &file_internal_social_service_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_internal_social_service_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowUserRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *UnfollowUserRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type UnfollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserResponse) Reset() {
	*x = UnfollowUserResponse{}
	mi := &file_internal_social_service_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserResponse) ProtoMessage() {}

func (x *UnfollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserResponse.ProtoReflect.Descriptor instead.
func (*UnfollowUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IsFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_internal_social_service_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{4}
}

func (x *IsFollowingRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *IsFollowingRequest) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type IsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResponse) Reset() {
	*x = IsFollowingResponse{}
	mi := &file_internal_social_service_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResponse) ProtoMessage() {}

func (x *IsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResponse.ProtoReflect.Descriptor instead.
func (*IsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{5}
}

func (x *IsFollowingResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type FollowCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowCheck) Reset() {
	*x = FollowCheck{}
	mi := &file_internal_social_service_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowCheck) ProtoMessage() {}

func (x *FollowCheck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowCheck.ProtoReflect.Descriptor instead.
func (*FollowCheck) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{6}
}

func (x *FollowCheck) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowCheck) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

type FollowStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    string                 `protobuf:"bytes,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,3,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowStatus) Reset() {
	*x = FollowStatus{}
	mi := &file_internal_social_service_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowStatus) ProtoMessage() {}

func (x *FollowStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowStatus.ProtoReflect.Descriptor instead.
func (*FollowStatus) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{7}
}

func (x *FollowStatus) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowStatus) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

func (x *FollowStatus) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type BatchIsFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*FollowCheck         `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsFollowingRequest) Reset() {
	*x = BatchIsFollowingRequest{}
	mi := &file_internal_social_service_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsFollowingRequest) ProtoMessage() {}

func (x *BatchIsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsFollowingRequest.ProtoReflect.Descriptor instead.
func (*BatchIsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{8}
}

func (x *BatchIsFollowingRequest) GetChecks() []*FollowCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type BatchIsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*FollowStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsFollowingResponse) Reset() {
	*x = BatchIsFollowingResponse{}
	mi := &file_internal_social_service_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsFollowingResponse) ProtoMessage() {}

func (x *BatchIsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsFollowingResponse.ProtoReflect.Descriptor instead.
func (*BatchIsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{9}
}

func (x *BatchIsFollowingResponse) GetStatuses() []*FollowStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`  // e.g. 20
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // last seen follow_id or timestamp for BTree thing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_internal_social_service_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{10}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_internal_social_service_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{11}
}

func (x *GetFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowingRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FollowingEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeId    string                 `protobuf:"bytes,1,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	FollowedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowingEdge) Reset() {
	*x = FollowingEdge{}
	mi := &file_internal_social_service_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowingEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowingEdge) ProtoMessage() {}

func (x *FollowingEdge) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowingEdge.ProtoReflect.Descriptor instead.
func (*FollowingEdge) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{12}
}

func (x *FollowingEdge) GetFolloweeId() string {
	if x != nil {
		return x.FolloweeId
	}
	return ""
}

func (x *FollowingEdge) GetFollowedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowedAt
	}
	return nil
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Following     []*FollowingEdge       `protobuf:"bytes,1,rep,name=following,proto3" json:"following,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_internal_social_service_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{13}
}

func (x *GetFollowingResponse) GetFollowing() []*FollowingEdge {
	if x != nil {
		return x.Following
	}
	return nil
}

func (x *GetFollowingResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_internal_social_service_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{14}
}

func (x *GetFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFollowersRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type FollowerEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    string                 `protobuf:"bytes,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FollowedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=followed_at,json=followedAt,proto3" json:"followed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerEdge) Reset() {
	*x = FollowerEdge{}
	mi := &file_internal_social_service_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerEdge) ProtoMessage() {}

func (x *FollowerEdge) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerEdge.ProtoReflect.Descriptor instead.
func (*FollowerEdge) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{15}
}

func (x *FollowerEdge) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *FollowerEdge) GetFollowedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FollowedAt
	}
	return nil
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*FollowerEdge        `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_internal_social_service_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_social_service_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_internal_social_service_social_proto_rawDescGZIP(), []int{16}
}

func (x *GetFollowersResponse) GetFollowers() []*FollowerEdge {
	if x != nil {
		return x.Followers
	}
	return nil
}

func (x *GetFollowersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_internal_social_service_social_proto protoreflect.FileDescriptor

const file_internal_social_service_social_proto_rawDesc = "" +
	"\n" +
	"$internal/social-service/social.proto\x12\x06social\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x11FollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\".\n" +
	"\x12FollowUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x13UnfollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\"0\n" +
	"\x14UnfollowUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x12IsFollowingRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\"8\n" +
	"\x13IsFollowingResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\"O\n" +
	"\vFollowCheck\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\"s\n" +
	"\fFollowStatus\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\tR\n" +
	"followeeId\x12!\n" +
	"\fis_following\x18\x03 \x01(\bR\visFollowing\"F\n" +
	"\x17BatchIsFollowingRequest\x12+\n" +
	"\x06checks\x18\x01 \x03(\v2\x13.social.FollowCheckR\x06checks\"L\n" +
	"\x18BatchIsFollowingResponse\x120\n" +
	"\bstatuses\x18\x01 \x03(\v2\x14.social.FollowStatusR\bstatuses\":\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"b\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.social.PaginationR\n" +
	"pagination\"m\n" +
	"\rFollowingEdge\x12\x1f\n" +
	"\vfollowee_id\x18\x01 \x01(\tR\n" +
	"followeeId\x12;\n" +
	"\vfollowed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"followedAt\"l\n" +
	"\x14GetFollowingResponse\x123\n" +
	"\tfollowing\x18\x01 \x03(\v2\x15.social.FollowingEdgeR\tfollowing\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"b\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.social.PaginationR\n" +
	"pagination\"l\n" +
	"\fFollowerEdge\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\tR\n" +
	"followerId\x12;\n" +
	"\vfollowed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"followedAt\"k\n" +
	"\x14GetFollowersResponse\x122\n" +
	"\tfollowers\x18\x01 \x03(\v2\x14.social.FollowerEdgeR\tfollowers\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor2\xd4\x03\n" +
	"\rFollowService\x12C\n" +
	"\n" +
	"FollowUser\x12\x19.social.FollowUserRequest\x1a\x1a.social.FollowUserResponse\x12I\n" +
	"\fUnfollowUser\x12\x1b.social.UnfollowUserRequest\x1a\x1c.social.UnfollowUserResponse\x12F\n" +
	"\vIsFollowing\x12\x1a.social.IsFollowingRequest\x1a\x1b.social.IsFollowingResponse\x12U\n" +
	"\x10BatchIsFollowing\x12\x1f.social.BatchIsFollowingRequest\x1a .social.BatchIsFollowingResponse\x12I\n" +
	"\fGetFollowing\x12\x1b.social.GetFollowingRequest\x1a\x1c.social.GetFollowingResponse\x12I\n" +
	"\fGetFollowers\x12\x1b.social.GetFollowersRequest\x1a\x1c.social.GetFollowersResponseB\vZ\tsocialpb/b\x06proto3"

var (
	file_internal_social_service_social_proto_rawDescOnce sync.Once
	file_internal_social_service_social_proto_rawDescData []byte
)

func file_internal_social_service_social_proto_rawDescGZIP() []byte {
	file_internal_social_service_social_proto_rawDescOnce.Do(func() {
		file_internal_social_service_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_social_service_social_proto_rawDesc), len(file_internal_social_service_social_proto_rawDesc)))
	})
	return file_internal_social_service_social_proto_rawDescData
}

var file_internal_social_service_social_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_social_service_social_proto_goTypes = []any{
	(*FollowUserRequest)(nil),        // 0: social.FollowUserRequest
	(*FollowUserResponse)(nil),       // 1: social.FollowUserResponse
	(*UnfollowUserRequest)(nil),      // 2: social.UnfollowUserRequest
	(*UnfollowUserResponse)(nil),     // 3: social.UnfollowUserResponse
	(*IsFollowingRequest)(nil),       // 4: social.IsFollowingRequest
	(*IsFollowingResponse)(nil),      // 5: social.IsFollowingResponse
	(*FollowCheck)(nil),              // 6: social.FollowCheck
	(*FollowStatus)(nil),             // 7: social.FollowStatus
	(*BatchIsFollowingRequest)(nil),  // 8: social.BatchIsFollowingRequest
	(*BatchIsFollowingResponse)(nil), // 9: social.BatchIsFollowingResponse
	(*Pagination)(nil),               // 10: social.Pagination
	(*GetFollowingRequest)(nil),      // 11: social.GetFollowingRequest
	(*FollowingEdge)(nil),            // 12: social.FollowingEdge
	(*GetFollowingResponse)(nil),     // 13: social.GetFollowingResponse
	(*GetFollowersRequest)(nil),      // 14: social.GetFollowersRequest
	(*FollowerEdge)(nil),             // 15: social.FollowerEdge
	(*GetFollowersResponse)(nil),     // 16: social.GetFollowersResponse
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
}
var file_internal_social_service_social_proto_depIdxs = []int32{
	6,  // 0: social.BatchIsFollowingRequest.checks:type_name -> social.FollowCheck
	7,  // 1: social.BatchIsFollowingResponse.statuses:type_name -> social.FollowStatus
	10, // 2: social.GetFollowingRequest.pagination:type_name -> social.Pagination
	17, // 3: social.FollowingEdge.followed_at:type_name -> google.protobuf.Timestamp
	12, // 4: social.GetFollowingResponse.following:type_name -> social.FollowingEdge
	10, // 5: social.GetFollowersRequest.pagination:type_name -> social.Pagination
	17, // 6: social.FollowerEdge.followed_at:type_name -> google.protobuf.Timestamp
	15, // 7: social.GetFollowersResponse.followers:type_name -> social.FollowerEdge
	0,  // 8: social.FollowService.FollowUser:input_type -> social.FollowUserRequest
	2,  // 9: social.FollowService.UnfollowUser:input_type -> social.UnfollowUserRequest
	4,  // 10: social.FollowService.IsFollowing:input_type -> social.IsFollowingRequest
	8,  // 11: social.FollowService.BatchIsFollowing:input_type -> social.BatchIsFollowingRequest
	11, // 12: social.FollowService.GetFollowing:input_type -> social.GetFollowingRequest
	14, // 13: social.FollowService.GetFollowers:input_type -> social.GetFollowersRequest
	1,  // 14: social.FollowService.FollowUser:output_type -> social.FollowUserResponse
	3,  // 15: social.FollowService.UnfollowUser:output_type -> social.UnfollowUserResponse
	5,  // 16: social.FollowService.IsFollowing:output_type -> social.IsFollowingResponse
	9,  // 17: social.FollowService.BatchIsFollowing:output_type -> social.BatchIsFollowingResponse
	13, // 18: social.FollowService.GetFollowing:output_type -> social.GetFollowingResponse
	16, // 19: social.FollowService.GetFollowers:output_type -> social.GetFollowersResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_social_service_social_proto_init() }
func file_internal_social_service_social_proto_init() {
	if File_internal_social_service_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_social_service_social_proto_rawDesc), len(file_internal_social_service_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_social_service_social_proto_goTypes,
		DependencyIndexes: file_internal_social_service_social_proto_depIdxs,
		MessageInfos:      file_internal_social_service_social_proto_msgTypes,
	}.Build()
	File_internal_social_service_social_proto = out.File
	file_internal_social_service_social_proto_goTypes = nil
	file_internal_social_service_social_proto_depIdxs = nil
}
